---
- name: "check fs structure"
  fail:
    msg: "{{item.mnt}} is missing something"
  loop: "{{lvm_encfs}}"
  failed_when: >-
    item.key|default('') == '' or
    item.size|default('') == '' or
    item.size|float == 0

- name: "check if mounted first"
  fail:
    msg: "{{item.mnt}} not mounted"
  register: mnt_check
  ignore_errors: true
  changed_when: false
  failed_when: >-
    '/mnt/' + item.mnt not in ansible_mounts | map(attribute='mount')
  loop: "{{lvm_encfs}}"

- name: "no shrink only grow"
  fail:
    msg: "checking sizes of {{item.mnt}}"
  loop: "{{lvm_encfs}}"
  failed_when: >-
    item.mnt + '-' + lvm_crypt_suffix in ansible_lvm['lvs'] and
    ansible_lvm['lvs'][item.mnt + '-' + lvm_crypt_suffix]['size_g']|float
      > item.size|float

- name: "cannot change volume group"
  fail:
    msg: "checking volume gruop for {{item.mnt}}"
  failed_when: >-
    item.mnt + '-' + lvm_crypt_suffix in ansible_lvm['lvs'] and
    ansible_lvm['lvs'][item.mnt + '-' + lvm_crypt_suffix]['vg'] != vg
  loop: "{{lvm_encfs}}"

- name: "ensure crypto logical volume"
  lvol:
    lv: "{{item.mnt}}-{{lvm_crypt_suffix}}"
    size: "{{item.size}}G"
    vg: "{{vg}}"
    shrink: false
  loop: "{{lvm_encfs}}"

- name: "copy keys"
  copy:
    src: "{{lvm_key_source}}/{{item.item.key}}.key"
    dest: "{{lvm_key_dest}}/{{item.item.key}}"
    mode: "0600"
  when: item.failed_when_result
  loop: "{{mnt_check.results}}"
  no_log: true

- name: "manage luks"
  luks_device:
    device: "/dev/{{vg}}/{{item.item.mnt}}-{{lvm_crypt_suffix}}"
    keyfile: "{{lvm_key_dest}}/{{item.item.key}}"
    name: "{{item.item.mnt}}"
    state: "opened"
  loop: "{{mnt_check.results}}"
  when: item.failed_when_result

- name: "resize luks if needed"
  shell: >-
    cryptsetup resize
    --key-file={{lvm_key_dest}}/{{item.key}}.key {{item.mnt}}
  loop: "{{lvm_encfs}}"
  when: >-
    item.mnt + '-' + lvm_crypt_suffix in ansible_lvm['lvs']
    and item.size|float != (ansible_lvm['lvs']
      [item.mnt + '-' + lvm_crypt_suffix]['size_g'])|float

- name: "ensure fs"
  filesystem:
    dev: "/dev/mapper/{{item.mnt}}"
    fstype: "ext4"
    resizefs: true
  loop: "{{lvm_encfs}}"

- name: "ensure directory exists"
  file:
    path: "{{item.mnt_prefix|default(lvm_default_mnt_prefix)}}/{{item.mnt}}"
    state: directory
  with_items: "{{lvm_encfs}}"

- name: "mount encrypted filesystem"
  mount:
    fstype: "ext4"
    path: "{{item.item.mnt_prefix|default(lvm_default_mnt_prefix)}}/{{item.item.mnt}}"
    src: "/dev/mapper/{{item.item.mnt}}"
    state: "mounted"
  loop: "{{mnt_check.results}}"

- name: "remove keys"
  file:
    path: "{{lvm_key_dest}}/{{item.key}}"
    state: absent
  loop: "{{lvm_encfs}}"
