---
- name: "create key file location"
  file:
    path: "{{lvm_key_dest}}"
    state: "directory"
    mode: "0400"
    owner: "root"
    group: "root"

- name: "create volume group and associate physical volumes"
  lvg:
    state: "present"
    vg: "{{vg}}"
    pvs: "{{pv}}"

- include_tasks: "encfs.yml"

- include_tasks: "plain.yml"
