---
- name: "check plain var structure"
  fail:
    msg: "{{item.mnt}} is missing something"
  loop: "{{lvm_plain}}"
  failed_when: >-
    item.size|default('') == '' or
    item.size|float == 0

- name: "check if mounted first"
  fail:
    msg: "{{item.mnt}} not mounted"
  register: mnt_check
  ignore_errors: true
  changed_when: false
  failed_when: >-
    '/mnt/' + item.mnt not in ansible_mounts | map(attribute='mount')
  loop: "{{lvm_plain}}"

- name: "no shrink only grow"
  fail:
    msg: "checking sizes of {{item.mnt}}"
  loop: "{{lvm_plain}}"
  failed_when: >-
    item.mnt in ansible_lvm['lvs'] and
    (ansible_lvm['lvs'][item.mnt]['size_g'])|float
      > item.size|float

- name: "cannot change volume group"
  fail:
    msg: "checking volume gruop for {{item.mnt}}"
  failed_when: >-
    item.mnt in ansible_lvm['lvs'] and
    ansible_lvm['lvs'][item.mnt]['vg'] != vg
  loop: "{{lvm_plain}}"

- name: "ensure plain logical volume"
  lvol:
    lv: "{{item.mnt}}"
    size: "{{item.size}}G"
    vg: "{{vg}}"
    shrink: false
  loop: "{{lvm_plain}}"

- name: "ensure fs"
  filesystem:
    dev: "/dev/{{vg}}/{{item.mnt}}"
    fstype: "ext4"
    resizefs: true
  loop: "{{lvm_plain}}"

- name: "mount plain filesystem"
  mount:
    boot: false
    fstype: "ext4"
    path: "{{item.item.mnt_prefix|default(lvm_default_mnt_prefix)}}/{{item.item.mnt}}"
    src: "/dev/{{vg}}/{{item.item.mnt}}"
    state: "mounted"
  loop: "{{mnt_check.results}}"
